package com.ade.open.api.server.persistent.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.ade.open.api.server.persistent.TOpenSecretService;
import com.ade.open.api.server.persistent.TOpenSecretVm;

/**
 * Class _TOpenSecret was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TOpenSecret extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String SECRET_ID_PK_COLUMN = "SECRET_ID";

    public static final Property<Integer> COMPANY_ID = Property.create("companyId", Integer.class);
    public static final Property<LocalDateTime> CTIME = Property.create("ctime", LocalDateTime.class);
    public static final Property<Integer> CTOR = Property.create("ctor", Integer.class);
    public static final Property<Integer> ENABLE = Property.create("enable", Integer.class);
    public static final Property<Integer> GLOBAL = Property.create("global", Integer.class);
    public static final Property<String> PUBLIC_ID = Property.create("publicId", String.class);
    public static final Property<String> SECRET_VALUE = Property.create("secretValue", String.class);
    public static final Property<LocalDateTime> UTIME = Property.create("utime", LocalDateTime.class);
    public static final Property<Integer> UTOR = Property.create("utor", Integer.class);
    public static final Property<List<TOpenSecretService>> SECRET_SERVICE = Property.create("secretService", List.class);
    public static final Property<List<TOpenSecretVm>> SECRET_VM = Property.create("secretVm", List.class);

    public void setCompanyId(Integer companyId) {
        writeProperty("companyId", companyId);
    }
    public Integer getCompanyId() {
        return (Integer)readProperty("companyId");
    }

    public void setCtime(LocalDateTime ctime) {
        writeProperty("ctime", ctime);
    }
    public LocalDateTime getCtime() {
        return (LocalDateTime)readProperty("ctime");
    }

    public void setCtor(Integer ctor) {
        writeProperty("ctor", ctor);
    }
    public Integer getCtor() {
        return (Integer)readProperty("ctor");
    }

    public void setEnable(Integer enable) {
        writeProperty("enable", enable);
    }
    public Integer getEnable() {
        return (Integer)readProperty("enable");
    }

    public void setGlobal(Integer global) {
        writeProperty("global", global);
    }
    public Integer getGlobal() {
        return (Integer)readProperty("global");
    }

    public void setPublicId(String publicId) {
        writeProperty("publicId", publicId);
    }
    public String getPublicId() {
        return (String)readProperty("publicId");
    }

    public void setSecretValue(String secretValue) {
        writeProperty("secretValue", secretValue);
    }
    public String getSecretValue() {
        return (String)readProperty("secretValue");
    }

    public void setUtime(LocalDateTime utime) {
        writeProperty("utime", utime);
    }
    public LocalDateTime getUtime() {
        return (LocalDateTime)readProperty("utime");
    }

    public void setUtor(Integer utor) {
        writeProperty("utor", utor);
    }
    public Integer getUtor() {
        return (Integer)readProperty("utor");
    }

    public void addToSecretService(TOpenSecretService obj) {
        addToManyTarget("secretService", obj, true);
    }
    public void removeFromSecretService(TOpenSecretService obj) {
        removeToManyTarget("secretService", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TOpenSecretService> getSecretService() {
        return (List<TOpenSecretService>)readProperty("secretService");
    }


    public void addToSecretVm(TOpenSecretVm obj) {
        addToManyTarget("secretVm", obj, true);
    }
    public void removeFromSecretVm(TOpenSecretVm obj) {
        removeToManyTarget("secretVm", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TOpenSecretVm> getSecretVm() {
        return (List<TOpenSecretVm>)readProperty("secretVm");
    }


}
