package com.ade.open.api.server.persistent.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TOpenServiceHis was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TOpenServiceHis extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Integer> GLOBAL = Property.create("global", Integer.class);
    public static final Property<String> PUBLIC_ID = Property.create("publicId", String.class);
    public static final Property<String> REQUEST_CONTEXT = Property.create("requestContext", String.class);
    public static final Property<String> REQUEST_IP = Property.create("requestIp", String.class);
    public static final Property<LocalDateTime> REQUEST_TIME = Property.create("requestTime", LocalDateTime.class);
    public static final Property<String> RESPONSE_CONTEXT = Property.create("responseContext", String.class);
    public static final Property<LocalDateTime> RESPONSE_TIME = Property.create("responseTime", LocalDateTime.class);

    public void setGlobal(int global) {
        writeProperty("global", global);
    }
    public int getGlobal() {
        Object value = readProperty("global");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPublicId(String publicId) {
        writeProperty("publicId", publicId);
    }
    public String getPublicId() {
        return (String)readProperty("publicId");
    }

    public void setRequestContext(String requestContext) {
        writeProperty("requestContext", requestContext);
    }
    public String getRequestContext() {
        return (String)readProperty("requestContext");
    }

    public void setRequestIp(String requestIp) {
        writeProperty("requestIp", requestIp);
    }
    public String getRequestIp() {
        return (String)readProperty("requestIp");
    }

    public void setRequestTime(LocalDateTime requestTime) {
        writeProperty("requestTime", requestTime);
    }
    public LocalDateTime getRequestTime() {
        return (LocalDateTime)readProperty("requestTime");
    }

    public void setResponseContext(String responseContext) {
        writeProperty("responseContext", responseContext);
    }
    public String getResponseContext() {
        return (String)readProperty("responseContext");
    }

    public void setResponseTime(LocalDateTime responseTime) {
        writeProperty("responseTime", responseTime);
    }
    public LocalDateTime getResponseTime() {
        return (LocalDateTime)readProperty("responseTime");
    }

}
