package com.ade.open.api.server.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.ade.open.api.server.persistent.TOpenSecretService;

/**
 * Class _TOpenService was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TOpenService extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String SERVICE_ID_PK_COLUMN = "SERVICE_ID";

    public static final Property<String> SERVICE_DESC = Property.create("serviceDesc", String.class);
    public static final Property<String> SERVICE_NAME = Property.create("serviceName", String.class);
    public static final Property<List<TOpenSecretService>> SERVICE_SECRET = Property.create("serviceSecret", List.class);

    public void setServiceDesc(String serviceDesc) {
        writeProperty("serviceDesc", serviceDesc);
    }
    public String getServiceDesc() {
        return (String)readProperty("serviceDesc");
    }

    public void setServiceName(String serviceName) {
        writeProperty("serviceName", serviceName);
    }
    public String getServiceName() {
        return (String)readProperty("serviceName");
    }

    public void addToServiceSecret(TOpenSecretService obj) {
        addToManyTarget("serviceSecret", obj, true);
    }
    public void removeFromServiceSecret(TOpenSecretService obj) {
        removeToManyTarget("serviceSecret", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TOpenSecretService> getServiceSecret() {
        return (List<TOpenSecretService>)readProperty("serviceSecret");
    }


}
